
/*if((dma_buffer[0]==(uint8_t)('1'))&&(dma_buffer[1]==(uint8_t)('1'))&&(dma_buffer[2]==(uint8_t)('1'))){
					LED_ON(9);
				}
				else{
					LED_OFF(9);
				}
				if((dma_buffer[3]==(uint8_t)('2'))&&(dma_buffer[4]==(uint8_t)('2'))&&(dma_buffer[5]==(uint8_t)('2'))){
					LED_ON(8);
				}
				else{
					LED_OFF(8);
				}
				if((dma_buffer[6]==(uint8_t)('3'))&&(dma_buffer[7]==(uint8_t)('3'))&&(dma_buffer[8]==(uint8_t)('3'))){
					LED_ON(7);
				}
				else{
					LED_OFF(7);
				}
				if((dma_buffer[9]==(uint8_t)('4'))&&(dma_buffer[10]==(uint8_t)('4'))&&(dma_buffer[11]==(uint8_t)('4'))){
					LED_ON(6);
				}
				else{
					LED_OFF(6);
				}
				if((dma_buffer[12]==(uint8_t)('5'))&&(dma_buffer[13]==(uint8_t)('5'))&&(dma_buffer[14]==(uint8_t)('5'))){
					LED_ON(5);
				}
				else{
					LED_OFF(5);
				}
				if((dma_buffer[15]==(uint8_t)('6'))&&(dma_buffer[16]==(uint8_t)('6'))&&(dma_buffer[17]==(uint8_t)('6'))){
					LED_ON(4);
				}
				else{
					LED_OFF(4);
				}*/
				